### ISSUE TITLE
Add --dry-run mode to muninn-update

### ISSUE THREAD

**Issue by bruno-rino** [stcorp/muninn#26]
This mode would only show the differences (without applying them).

**Comment by svniemeijer** [comment]
This looks problematic.

For the 'ingest' and 'pull' actions muninn-update does not calculate differences with regard to the current property set but just overwrites all properties with whatever comes back from the product type extension. So determining differences would be a much more complicated operation.

And also, for the post_ingest and post_pull there is not even a way to determine differences, since it is just a call to a plugin hook function.

I will therefore close this issue, since it looks like a too complicated nice-to-have.
